
#ifndef KEYBOARD_ANORAK_SPLITBRAIN_BACKLIGHT_ANIMATIONS_TYPE_O_MATIC_H_
#define KEYBOARD_ANORAK_SPLITBRAIN_BACKLIGHT_ANIMATIONS_TYPE_O_MATIC_H_

void type_o_matic_animation_start(void);
void type_o_matic_animation_loop(void);
void type_o_matic_animation_stop(void);

#endif /* KEYBOARD_ANORAK_SPLITBRAIN_BACKLIGHT_ANIMATIONS_TYPE_O_MATIC_H_ */
