#ifndef KEYBOARD_ANORAK_SPLITBRAIN_BACKLIGHT_TWI_CONFIG_H_
#define KEYBOARD_ANORAK_SPLITBRAIN_BACKLIGHT_TWI_CONFIG_H_

#define AVR315 1
#define BUFFTW 2

#define TWILIB BUFFTW

#define TWI_SEND_DATA_BUFFER_SIZE 150

#endif /* KEYBOARD_ANORAK_SPLITBRAIN_BACKLIGHT_TWI_CONFIG_H_ */
