#ifndef KEYBOARD_ANORAK_91TKL_BACKLIGHT_TWI_CONFIG_H_
#define KEYBOARD_ANORAK_91TKL_BACKLIGHT_TWI_CONFIG_H_

#define TWI_SEND_DATA_BUFFER_SIZE 144+2
#include "avr315/TWI_Master.h"

#endif /* KEYBOARD_ANORAK_91TKL_BACKLIGHT_TWI_CONFIG_H_ */
